### ISSUE TITLE
モデルの作成

### ISSUE THREAD

**Issue by n06Ar** [nanas773/kpt#19]
## 概要
Modelクラスが、UsersテーブルのModelクラスしかないため、他のテーブルのModelクラスを作成する
下記の画像がKPTで使用するTableです
https://github.com/nanas773/kpt-design/blob/main/database_er_diagram.png

### 注意
* Modelクラスは、`app/Models/`に作成すること
* 作成する際はテーブル名を単数系にすること
  - 例）Users  → User

### 作成対象のテーブル
* Goals
* Tasks
* Team_Users

## 参考資料

* `php artisan make:model {モデル名}`
  - これを使えばうまくできそう
* https://readouble.com/laravel/8.x/ja/eloquent.html
  - マイグレーションは作成済みなので作成不要

**Comment by ykyk1218** [comment]
対応済み
